import random
import datetime

# Generated by ChatGPT

# -----------------------------------------
# Tournament date ranges
# -----------------------------------------
tournaments = {
    '2021_M1': ('2021-05-24', '2021-05-31'),
    '2021_M2': ('2021-09-10', '2021-09-20'),
    '2021_C1': ('2021-12-01', '2021-12-12'),
    '2022_M1': ('2022-04-10', '2022-04-24'),
    '2022_M2': ('2022-07-10', '2022-07-24'),
    '2022_C1': ('2022-08-31', '2022-09-19'),
    '2023_M1': ('2023-06-11', '2023-06-25'),
    '2023_C1': ('2023-08-07', '2023-08-27'),
    '2024_M1': ('2024-03-14', '2024-03-24'),
    '2024_M2': ('2024-05-23', '2024-06-10'),
    '2024_C1': ('2024-08-01', '2024-08-25'),
    '2025_M1': ('2025-02-20', '2025-03-03'),
    '2025_M2': ('2025-06-08', '2025-06-22'),
    '2025_C1': ('2025-09-12', '2025-10-06'),
}

# -----------------------------------------
# Name generation pools
# -----------------------------------------
first_names = [
    "Alice","Brandon","Cara","Daniel","Emma","Felix","Grace","Hiro","Isabela","James","Karla","Liam","Maya",
    "Noah","Olivia","Pablo","Quincy","Rina","Samuel","Tara","Umar","Violet","William","Xinyi","Yara","Zane",
    "Adrian","Bianca","Carter","Dana","Evan","Fiona","Gavin","Hailey","Ivan","Janet","Aaron","Bella","Carlos",
    "Diana","Ethan","Faith","Gabe","Hannah","Ian","Jenna","Kyle","Laura","Mark","Nina","Oscar","Paula","Ronnie",
    "Samantha","Troy","Uma","Victor","Wendy","Xavier","Yvonne","Zachary","Maribel","Owen","Kylie","Brent",
    "Fiona","Tristan","Nicole","Ethan","Sasha","Riley","Chloe","Marcus","Toby","Larissa","Hector","Kelly",
    "Ramon","Leila","Goro","Celine","Soren","Vivian","Jiro","Hannah","Oliver","Julie","Nathan","Amanda",
]

last_names = [
    "Reyes","Lee","Martinez","Cruz","Johnson","Tan","Park","Sato","Liu","Miller","Villanueva","Walker","Chen",
    "Davis","Zhang","Rivera","Howard","Kawaguchi","Ortiz","Wilson","Shah","Adams","Scott","Liu","Gomez",
    "Foster","Vega","Flores","Hayes","Oliver","Cruz","Rogers","Russell","Owens","Douglas","Ellis","Johnson",
    "Smith","Reyes","Carter","Hale","Park","Torres","Lancaster","Miles","Simmons","Turner","Delgado","Ramirez",
    "Brooks","Gibson","Walker","Adams","Bennett","Greene","Caldwell","Hudson","Patterson","Grant","Parker",
]

payment_methods = ["Credit Card", "Debit Card", "PayPal", "Cash", "GCash"]

# -----------------------------------------
# Helper functions
# -----------------------------------------
def random_date(start, end):
    start_dt = datetime.datetime.strptime(start, "%Y-%m-%d")
    end_dt = datetime.datetime.strptime(end, "%Y-%m-%d")
    delta = (end_dt - start_dt).days
    random_day = random.randint(0, delta)
    return (start_dt + datetime.timedelta(days=random_day)).strftime("%Y-%m-%d")

def generate_seat(existing):
    while True:
        section = random.choice("ABCDEFGHIJKLMNOPQRSTUVWXYZ")
        seat_num = random.randint(1, 999)
        seat = f"{section}{seat_num:03d}"
        if seat not in existing:
            existing.add(seat)
            return seat

# -----------------------------------------
# Generate attendees
# -----------------------------------------
sql_entries = []
seat_used = {t: set() for t in tournaments}

for i in range(5000):
    tournament = random.choice(list(tournaments.keys()))
    start, end = tournaments[tournament]
    date = random_date(start, end)
    fname = random.choice(first_names)
    lname = random.choice(last_names)
    name = f"{fname} {lname}"
    seat = generate_seat(seat_used[tournament])
    price = round(random.uniform(100, 300), 2)
    payment = random.choice(payment_methods)
    verified = random.randint(0, 1)

    sql_entries.append(
        f"('{name}', '{date}', '{tournament}', '{seat}', {price}, '{payment}', {verified})"
    )

# -----------------------------------------
# Output SQL
# -----------------------------------------
print("INSERT INTO attendee (customer_name, date_of_ticket, tournament_id, seat_id, ticket_price, mode_of_payment, verified) VALUES")
print(",\n".join(sql_entries) + ";")
