# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_match_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(654, 463)
        Dialog.setMinimumSize(QtCore.QSize(654, 462))
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(450, 420, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Qt::Orientation::Horizontal)
        self.buttonBox.setStandardButtons(QtCore.Qt.QDialogButtonBox::StandardButton::Cancel|QtCore.Qt.QDialogButtonBox::StandardButton::Save)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(100, 110, 461, 111))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.player_ign_2 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.player_ign_2.setObjectName("player_ign_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.player_ign_2)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.player_name_2 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.player_name_2.setObjectName("player_name_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.player_name_2)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.formLayoutWidget_3)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dateTimeEdit)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.player_name_3 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.player_name_3.setObjectName("player_name_3")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.player_name_3)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.formLayoutWidget_4 = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(100, 260, 461, 86))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.comboBox = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.comboBox.setObjectName("comboBox")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.comboBox_2.setObjectName("comboBox_2")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.comboBox_3 = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.comboBox_3.setObjectName("comboBox_3")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_3)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Match ID:"))
        self.label_6.setText(_translate("Dialog", "Tournament ID:"))
        self.label_8.setText(_translate("Dialog", "Bracket:"))
        self.label_7.setText(_translate("Dialog", "Date and Time:"))
        self.label_3.setText(_translate("Dialog", "Team 1:"))
        self.label_9.setText(_translate("Dialog", "Team 2:"))
        self.label_10.setText(_translate("Dialog", "Map:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
