# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_player_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_player_dialog(object):
    def setupUi(self, add_player_dialog):
        add_player_dialog.setObjectName("add_player_dialog")
        add_player_dialog.resize(654, 462)
        add_player_dialog.setMinimumSize(QtCore.QSize(654, 462))
        self.buttonBox = QtWidgets.QDialogButtonBox(add_player_dialog)
        self.buttonBox.setGeometry(QtCore.QRect(450, 420, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Qt::Orientation::Horizontal)
        self.buttonBox.setStandardButtons(QtCore.Qt.QDialogButtonBox::StandardButton::Cancel|QtCore.Qt.QDialogButtonBox::StandardButton::Save)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget_2 = QtWidgets.QWidget(add_player_dialog)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(90, 160, 461, 121))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.player_ign = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.player_ign.setObjectName("player_ign")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.player_ign)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.player_name = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.player_name.setObjectName("player_name")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.player_name)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.start_date = QtWidgets.QDateEdit(self.formLayoutWidget_2)
        self.start_date.setObjectName("start_date")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.start_date)
        self.team_name_dropdown = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.team_name_dropdown.setObjectName("team_name_dropdown")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.team_name_dropdown)

        self.retranslateUi(add_player_dialog)
        self.buttonBox.accepted.connect(add_player_dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(add_player_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(add_player_dialog)

    def retranslateUi(self, add_player_dialog):
        _translate = QtCore.QCoreApplication.translate
        add_player_dialog.setWindowTitle(_translate("add_player_dialog", "Dialog"))
        self.label.setText(_translate("add_player_dialog", "Player IGN"))
        self.label_3.setText(_translate("add_player_dialog", "Player Name:"))
        self.label_4.setText(_translate("add_player_dialog", "Team (Name or ID):"))
        self.label_5.setText(_translate("add_player_dialog", "Start Date:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_player_dialog = QtWidgets.QDialog()
    ui = Ui_add_player_dialog()
    ui.setupUi(add_player_dialog)
    add_player_dialog.show()
    sys.exit(app.exec_())
