# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_team_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_team_dialog(object):
    def setupUi(self, add_team_dialog):
        add_team_dialog.setObjectName("add_team_dialog")
        add_team_dialog.resize(654, 462)
        add_team_dialog.setMinimumSize(QtCore.QSize(654, 462))
        self.buttonBox = QtWidgets.QDialogButtonBox(add_team_dialog)
        self.buttonBox.setGeometry(QtCore.QRect(450, 420, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Qt::Orientation::Horizontal)
        self.buttonBox.setStandardButtons(QtCore.Qt.QDialogButtonBox::StandardButton::Cancel|QtCore.Qt.QDialogButtonBox::StandardButton::Save)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(add_team_dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(140, 190, 361, 81))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.team_id_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.team_id_input.setObjectName("team_id_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.team_id_input)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.team_name_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.team_name_input.setObjectName("team_name_input")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.team_name_input)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.region_dropdown = QtWidgets.QComboBox(self.formLayoutWidget)
        self.region_dropdown.setObjectName("region_dropdown")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.region_dropdown)

        self.retranslateUi(add_team_dialog)
        self.buttonBox.accepted.connect(add_team_dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(add_team_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(add_team_dialog)

    def retranslateUi(self, add_team_dialog):
        _translate = QtCore.QCoreApplication.translate
        add_team_dialog.setWindowTitle(_translate("add_team_dialog", "Dialog"))
        self.label.setText(_translate("add_team_dialog", "Team ID:"))
        self.label_3.setText(_translate("add_team_dialog", "Team Name:"))
        self.label_4.setText(_translate("add_team_dialog", "Region:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_team_dialog = QtWidgets.QDialog()
    ui = Ui_add_team_dialog()
    ui.setupUi(add_team_dialog)
    add_team_dialog.show()
    sys.exit(app.exec_())
