# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_tournament_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addTournamentDialog(object):
    def setupUi(self, addTournamentDialog):
        addTournamentDialog.setObjectName("addTournamentDialog")
        addTournamentDialog.resize(654, 462)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(addTournamentDialog.sizePolicy().hasHeightForWidth())
        addTournamentDialog.setSizePolicy(sizePolicy)
        addTournamentDialog.setMinimumSize(QtCore.QSize(654, 462))
        addTournamentDialog.setMaximumSize(QtCore.QSize(654, 462))
        addTournamentDialog.setBaseSize(QtCore.QSize(654, 462))
        self.cancelButton = QtWidgets.QDialogButtonBox(addTournamentDialog)
        self.cancelButton.setGeometry(QtCore.QRect(450, 420, 171, 32))
        self.cancelButton.setOrientation(QtCore.Qt.Qt::Orientation::Horizontal)
        self.cancelButton.setStandardButtons(QtCore.Qt.QDialogButtonBox::StandardButton::Cancel|QtCore.Qt.QDialogButtonBox::StandardButton::Save)
        self.cancelButton.setObjectName("cancelButton")
        self.formLayoutWidget_2 = QtWidgets.QWidget(addTournamentDialog)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(90, 120, 461, 223))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.tournament_add = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.tournament_add.setContentsMargins(0, 0, 0, 0)
        self.tournament_add.setObjectName("tournament_add")
        self.label = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tournament_add.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.tournament_addName = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.tournament_addName.setObjectName("tournament_addName")
        self.tournament_add.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tournament_addName)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.tournament_add.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.tournament_addPrizePool = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.tournament_addPrizePool.setObjectName("tournament_addPrizePool")
        self.tournament_add.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tournament_addPrizePool)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.tournament_add.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.tournament_addCountry = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.tournament_addCountry.setObjectName("tournament_addCountry")
        self.tournament_add.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.tournament_addCountry)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.tournament_add.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.tournament_addCity = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.tournament_addCity.setObjectName("tournament_addCity")
        self.tournament_add.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.tournament_addCity)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.tournament_add.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.tournament_addVenue = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.tournament_addVenue.setObjectName("tournament_addVenue")
        self.tournament_add.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.tournament_addVenue)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.tournament_add.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.tournament_addTypeDropdown = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.tournament_addTypeDropdown.setObjectName("tournament_addTypeDropdown")
        self.tournament_addTypeDropdown.addItem("")
        self.tournament_addTypeDropdown.addItem("")
        self.tournament_add.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tournament_addTypeDropdown)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.tournament_add.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.tournament_addStartDate = QtWidgets.QDateEdit(self.formLayoutWidget_2)
        self.tournament_addStartDate.setObjectName("tournament_addStartDate")
        self.tournament_add.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.tournament_addStartDate)

        self.retranslateUi(addTournamentDialog)
        self.cancelButton.accepted.connect(addTournamentDialog.accept) # type: ignore
        self.cancelButton.rejected.connect(addTournamentDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(addTournamentDialog)

    def retranslateUi(self, addTournamentDialog):
        _translate = QtCore.QCoreApplication.translate
        addTournamentDialog.setWindowTitle(_translate("addTournamentDialog", "Dialog"))
        self.label.setText(_translate("addTournamentDialog", "Tournament Name:"))
        self.label_4.setText(_translate("addTournamentDialog", "Prize Pool:"))
        self.label_8.setText(_translate("addTournamentDialog", "Country:"))
        self.label_9.setText(_translate("addTournamentDialog", "City:"))
        self.label_10.setText(_translate("addTournamentDialog", "Venue:"))
        self.label_3.setText(_translate("addTournamentDialog", "Tournament Type:"))
        self.tournament_addTypeDropdown.setItemText(0, _translate("addTournamentDialog", "Masters"))
        self.tournament_addTypeDropdown.setItemText(1, _translate("addTournamentDialog", "Champions"))
        self.label_5.setText(_translate("addTournamentDialog", "Start Date:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addTournamentDialog = QtWidgets.QDialog()
    ui = Ui_addTournamentDialog()
    ui.setupUi(addTournamentDialog)
    addTournamentDialog.show()
    sys.exit(app.exec_())
