# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'matchDetailsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_matchDetailsWindow(object):
    def setupUi(self, matchDetailsWindow):
        matchDetailsWindow.setObjectName("matchDetailsWindow")
        matchDetailsWindow.resize(963, 714)
        self.centralwidget = QtWidgets.QWidget(matchDetailsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.matchDetails_team1Table = QtWidgets.QTableView(self.centralwidget)
        self.matchDetails_team1Table.setGeometry(QtCore.QRect(20, 80, 931, 271))
        self.matchDetails_team1Table.setObjectName("matchDetails_team1Table")
        self.matchDetails_matchUpLabel = QtWidgets.QLabel(self.centralwidget)
        self.matchDetails_matchUpLabel.setGeometry(QtCore.QRect(340, 20, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.matchDetails_matchUpLabel.setFont(font)
        self.matchDetails_matchUpLabel.setObjectName("matchDetails_matchUpLabel")
        self.matchDetails_team1Label = QtWidgets.QLabel(self.centralwidget)
        self.matchDetails_team1Label.setGeometry(QtCore.QRect(20, 50, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.matchDetails_team1Label.setFont(font)
        self.matchDetails_team1Label.setObjectName("matchDetails_team1Label")
        self.matchDetails_team2Table = QtWidgets.QTableView(self.centralwidget)
        self.matchDetails_team2Table.setGeometry(QtCore.QRect(20, 400, 931, 271))
        self.matchDetails_team2Table.setObjectName("matchDetails_team2Table")
        self.matchDetails_team2Label = QtWidgets.QLabel(self.centralwidget)
        self.matchDetails_team2Label.setGeometry(QtCore.QRect(20, 370, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.matchDetails_team2Label.setFont(font)
        self.matchDetails_team2Label.setObjectName("matchDetails_team2Label")
        self.matchDetails_scoreLabel = QtWidgets.QLabel(self.centralwidget)
        self.matchDetails_scoreLabel.setGeometry(QtCore.QRect(780, 20, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.matchDetails_scoreLabel.setFont(font)
        self.matchDetails_scoreLabel.setObjectName("matchDetails_scoreLabel")
        matchDetailsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(matchDetailsWindow)
        QtCore.QMetaObject.connectSlotsByName(matchDetailsWindow)

    def retranslateUi(self, matchDetailsWindow):
        _translate = QtCore.QCoreApplication.translate
        matchDetailsWindow.setWindowTitle(_translate("matchDetailsWindow", "MainWindow"))
        self.matchDetails_matchUpLabel.setText(_translate("matchDetailsWindow", "[INSERT MATCHUP AND TOURNAMENT]"))
        self.matchDetails_team1Label.setText(_translate("matchDetailsWindow", "[INSERT TEAM 1 NAME] Statistics"))
        self.matchDetails_team2Label.setText(_translate("matchDetailsWindow", "[INSERT TEAM 2 NAME] Statistics"))
        self.matchDetails_scoreLabel.setText(_translate("matchDetailsWindow", "Score: [INSERT SCORE]"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    matchDetailsWindow = QtWidgets.QMainWindow()
    ui = Ui_matchDetailsWindow()
    ui.setupUi(matchDetailsWindow)
    matchDetailsWindow.show()
    sys.exit(app.exec_())
