# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'playerDetailsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_playerDetailsWindow(object):
    def setupUi(self, playerDetailsWindow):
        playerDetailsWindow.setObjectName("playerDetailsWindow")
        playerDetailsWindow.resize(825, 671)
        self.centralwidget = QtWidgets.QWidget(playerDetailsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mvp_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mvp_label.setFont(font)
        self.mvp_label.setObjectName("mvp_label")
        self.gridLayout.addWidget(self.mvp_label, 9, 0, 1, 1)
        self.agentPicks_table = QtWidgets.QTableView(self.centralwidget)
        self.agentPicks_table.setObjectName("agentPicks_table")
        self.gridLayout.addWidget(self.agentPicks_table, 7, 0, 1, 1)
        self.teamHistory_table = QtWidgets.QTableView(self.centralwidget)
        self.teamHistory_table.setObjectName("teamHistory_table")
        self.gridLayout.addWidget(self.teamHistory_table, 5, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 8, 0, 1, 1)
        self.agentPicks_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.agentPicks_label.setFont(font)
        self.agentPicks_label.setObjectName("agentPicks_label")
        self.gridLayout.addWidget(self.agentPicks_label, 6, 0, 1, 1)
        self.playerStats_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.playerStats_label.setFont(font)
        self.playerStats_label.setObjectName("playerStats_label")
        self.gridLayout.addWidget(self.playerStats_label, 2, 0, 1, 1)
        self.playerStats_table = QtWidgets.QTableView(self.centralwidget)
        self.playerStats_table.setObjectName("playerStats_table")
        self.gridLayout.addWidget(self.playerStats_table, 3, 0, 1, 1)
        self.teamHistory_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.teamHistory_label.setFont(font)
        self.teamHistory_label.setObjectName("teamHistory_label")
        self.gridLayout.addWidget(self.teamHistory_label, 4, 0, 1, 1)
        self.playerName_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.playerName_label.setFont(font)
        self.playerName_label.setObjectName("playerName_label")
        self.gridLayout.addWidget(self.playerName_label, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        playerDetailsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(playerDetailsWindow)
        QtCore.QMetaObject.connectSlotsByName(playerDetailsWindow)

    def retranslateUi(self, playerDetailsWindow):
        _translate = QtCore.QCoreApplication.translate
        playerDetailsWindow.setWindowTitle(_translate("playerDetailsWindow", "MainWindow"))
        self.mvp_label.setText(_translate("playerDetailsWindow", "Number of MVPs: [INSERT NUMBER OF MVPS HERE]"))
        self.agentPicks_label.setText(_translate("playerDetailsWindow", "Agent Picks"))
        self.playerStats_label.setText(_translate("playerDetailsWindow", "Player Statistics"))
        self.teamHistory_label.setText(_translate("playerDetailsWindow", "Team History"))
        self.playerName_label.setText(_translate("playerDetailsWindow", "[Insert Player IGN] Details"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    playerDetailsWindow = QtWidgets.QMainWindow()
    ui = Ui_playerDetailsWindow()
    ui.setupUi(playerDetailsWindow)
    playerDetailsWindow.show()
    sys.exit(app.exec_())
