# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teamDetailsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_teamDetailsWindow(object):
    def setupUi(self, teamDetailsWindow):
        teamDetailsWindow.setObjectName("teamDetailsWindow")
        teamDetailsWindow.resize(721, 525)
        self.centralwidget = QtWidgets.QWidget(teamDetailsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.teamDetails = QtWidgets.QToolBox(self.centralwidget)
        self.teamDetails.setObjectName("teamDetails")
        self.teamDetails_placementHistory = QtWidgets.QWidget()
        self.teamDetails_placementHistory.setGeometry(QtCore.QRect(0, 0, 703, 399))
        self.teamDetails_placementHistory.setObjectName("teamDetails_placementHistory")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.teamDetails_placementHistory)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.teamDetails_placementHistory)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.teamDetails.addItem(self.teamDetails_placementHistory, "")
        self.teamDetails_matchHistory = QtWidgets.QWidget()
        self.teamDetails_matchHistory.setGeometry(QtCore.QRect(0, 0, 703, 399))
        self.teamDetails_matchHistory.setObjectName("teamDetails_matchHistory")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.teamDetails_matchHistory)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableView = QtWidgets.QTableView(self.teamDetails_matchHistory)
        self.tableView.setObjectName("tableView")
        self.gridLayout_3.addWidget(self.tableView, 0, 0, 1, 1)
        self.teamDetails.addItem(self.teamDetails_matchHistory, "")
        self.gridLayout.addWidget(self.teamDetails, 1, 0, 1, 1)
        teamDetailsWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(teamDetailsWindow)
        self.statusbar.setObjectName("statusbar")
        teamDetailsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(teamDetailsWindow)
        self.teamDetails.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(teamDetailsWindow)

    def retranslateUi(self, teamDetailsWindow):
        _translate = QtCore.QCoreApplication.translate
        teamDetailsWindow.setWindowTitle(_translate("teamDetailsWindow", "MainWindow"))
        self.label.setText(_translate("teamDetailsWindow", "[Insert Team Name] Details"))
        self.teamDetails.setItemText(self.teamDetails.indexOf(self.teamDetails_placementHistory), _translate("teamDetailsWindow", "Tournament Placements"))
        self.teamDetails.setItemText(self.teamDetails.indexOf(self.teamDetails_matchHistory), _translate("teamDetailsWindow", "Match History"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    teamDetailsWindow = QtWidgets.QMainWindow()
    ui = Ui_teamDetailsWindow()
    ui.setupUi(teamDetailsWindow)
    teamDetailsWindow.show()
    sys.exit(app.exec_())
